[package]
name = "identicode"
description = "code that identifies you"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/gulje/identicode"
license = "Apache-2.0"

[dependencies]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true